name: shell Commands

on: [push]

jobs:
  run-shell-command:
  	run-on: 
  	steps:
  		- name: echo a string
  		  run: echo "Hello World"
  		- name: multiline script
  		  run: |
  		  	node -v
  		  	npm -v