name: shell Commands

on: [push]

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "Hi Team"
            echo "How are you"
            echo "byee"
      - name: multiline script
        run:  |
          node -v
          npm -v
